# Generated by Django 5.1.6 on 2025-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.BigIntegerField(default=0),
        ),
    ]
