# Generated by Django 5.1.6 on 2025-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="postal_code",
            field=models.CharField(max_length=11),
        ),
    ]
