# Generated by Django 5.2.3 on 2025-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_options_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_business_user",
            field=models.BooleanField(default=False),
        ),
    ]
