# Generated by Django 5.2.3 on 2025-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_is_business_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit",
            field=models.BigIntegerField(default=0),
        ),
    ]
