# Generated by Django 5.2.3 on 2025-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_number",
            field=models.BigIntegerField(default=0),
        ),
    ]
