# Generated by Django 5.2.3 on 2025-06-26 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_address_intrducer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="intrducer",
        ),
        migrations.AddField(
            model_name="user",
            name="intrducer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_business_user": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intrducer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
