# Generated by Django 5.2.3 on 2025-06-26 21:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="dicription",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
