# Generated by Django 5.2.3 on 2025-08-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_report_dicription"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="next_page",
            field=models.TextField(blank=True, null=True),
        ),
    ]
