# Generated by Django 5.1.6 on 2025-06-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sell_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="color",
            new_name="condition",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="region",
        ),
    ]
