# Generated by Django 5.1.6 on 2025-03-29 00:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCharity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1500)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="more info about joband web site"
                    ),
                ),
                ("image", models.ImageField(upload_to="business/image")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=2500)),
                ("last_name", models.CharField(max_length=2500)),
                ("company_name", models.CharField(max_length=2500)),
                ("company_type", models.CharField(max_length=2500)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.BigIntegerField(default=0)),
                ("address", models.TextField()),
                ("discription", ckeditor_uploader.fields.RichTextUploadingField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="CharityAttr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=850)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="more info about service attr"
                    ),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
