# Generated by Django 5.1.6 on 2025-02-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutinfo",
            old_name="cotent",
            new_name="content",
        ),
    ]
