# Generated by Django 5.1.6 on 2025-02-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0002_rename_cotent_aboutinfo_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=950)),
                ("image", models.ImageField(upload_to="about/team/images")),
                ("twitter", models.TextField(help_text="twitter links")),
                ("facebook", models.TextField(help_text="facebook links")),
                ("google", models.TextField(help_text="google links")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
