# Generated by Django 5.1.6 on 2025-02-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0003_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2500)),
                ("image", models.ImageField(upload_to="about_us/image/brand")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(upload_to="about_us/image/team"),
        ),
    ]
