# Generated by Django 5.1.6 on 2025-03-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
