# Generated by Django 5.1.6 on 2025-03-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1500)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("message", models.TextField()),
            ],
        ),
    ]
