# Generated by Django 5.1.6 on 2025-05-05 17:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="SellProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("slug", models.SlugField(blank=True)),
                ("price", models.BigIntegerField(default=1)),
                (
                    "little_discription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image6",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="products",
                        to="sell.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=1500)),
                (
                    "discription",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                ("price", models.BigIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "sell_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_condition",
                        to="sell.sellproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage", models.CharField(max_length=1500)),
                ("price", models.BigIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "sell_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_storage",
                        to="sell.sellproduct",
                    ),
                ),
            ],
        ),
    ]
