# Generated by Django 5.2.3 on 2025-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0002_phonecategory_phonemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=1050, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=1050, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=1050, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=1050, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.RemoveField(
            model_name="sell",
            name="Full_name",
        ),
        migrations.RemoveField(
            model_name="sell",
            name="phone_number",
        ),
    ]
