# Generated by Django 5.2.3 on 2025-10-17 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0004_sellform_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellform",
            name="sell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sell.sell",
            ),
        ),
    ]
