# Generated by Django 5.2.3 on 2025-10-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0006_alter_sell_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonemodel",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="phone_model/image"
            ),
        ),
    ]
