# Generated by Django 5.1.6 on 2025-02-16 16:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opening_time", models.CharField(max_length=250)),
                ("call_number", models.BigIntegerField(default=0)),
                ("gmail_us", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MoreAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        blank=True, help_text="image of Attributes", null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "link",
                    models.TextField(
                        blank=True,
                        help_text="linke to read more about this attributes",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="MoreDiscripUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1500)),
                (
                    "littel_content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="little content about this part"
                    ),
                ),
                ("image1", models.ImageField(upload_to="home/morediscripUs")),
                ("image2", models.ImageField(upload_to="home/morediscripUs")),
                ("image3", models.ImageField(upload_to="home/morediscripUs")),
                ("links", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="home/poster/image"
                    ),
                ),
                (
                    "type1",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="we can change poster style with types",
                        null=True,
                    ),
                ),
                (
                    "type2",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="we can change poster style with types",
                        null=True,
                    ),
                ),
                (
                    "type3",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="we can change poster style with types",
                        null=True,
                    ),
                ),
                (
                    "linke",
                    models.TextField(
                        blank=True, help_text="links of button on posters", null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ShopAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "first_word",
                    models.CharField(help_text="first word on title", max_length=5),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("image", models.TextField(help_text="image of attributes")),
                (
                    "link",
                    models.TextField(
                        help_text="linke to read more about this attributes"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pinterest",
                    models.TextField(blank=True, help_text="pinterest_link", null=True),
                ),
                (
                    "google",
                    models.TextField(blank=True, help_text="google_link", null=True),
                ),
                (
                    "facebook",
                    models.TextField(blank=True, help_text="facebook_link", null=True),
                ),
                (
                    "twitter",
                    models.TextField(blank=True, help_text="twitter_link", null=True),
                ),
            ],
        ),
    ]
