# Generated by Django 5.1.6 on 2025-02-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poster",
            old_name="linke",
            new_name="link",
        ),
    ]
