# Generated by Django 5.1.6 on 2025-03-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_linke_poster_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedialinks",
            name="youtube",
            field=models.TextField(blank=True, help_text="youtube_link", null=True),
        ),
        migrations.AlterField(
            model_name="callinformation",
            name="call_number",
            field=models.CharField(max_length=250),
        ),
    ]
