# Generated by Django 5.1.6 on 2025-03-22 16:23

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350)),
                ("slug", models.SlugField()),
                ("price", models.BigIntegerField(default=1)),
                (
                    "little_discription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image4",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image5",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "image6",
                    models.ImageField(blank=True, null=True, upload_to="product/image"),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("on_sale", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="shop.comments",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_mobile",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
