# Generated by Django 5.1.6 on 2025-04-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_color_region_storage_product_color_product_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="region",
        ),
        migrations.RemoveField(
            model_name="product",
            name="storage",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products_color", to="shop.color"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products_region", to="shop.region"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products_storage",
                to="shop.storage",
            ),
        ),
    ]
