# Generated by Django 5.1.6 on 2025-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_product_color_remove_product_region_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
