# Generated by Django 5.1.6 on 2025-06-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_delete_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="region",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
    ]
