# Generated by Django 5.1.6 on 2025-06-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_product_region_delete_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="color",
            name="title",
        ),
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="storage",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="title",
        ),
        migrations.AddField(
            model_name="color",
            name="color",
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="color",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color",
                to="shop.product",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storage",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_storage",
                to="shop.product",
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="storage",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
