# Generated by Django 5.1.6 on 2025-06-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rename_storagedy_storage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color",
            old_name="title",
            new_name="color",
        ),
    ]
