# Generated by Django 5.1.6 on 2025-06-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_rename_storage_storage_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storage",
            old_name="title",
            new_name="storage",
        ),
    ]
