# Generated by Django 5.1.6 on 2025-02-23 20:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1500)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="more info about joband web site"
                    ),
                ),
                ("image", models.ImageField(upload_to="business/image")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
