# Generated by Django 5.1.6 on 2025-04-11 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("shop", "0005_delete_comments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discountcode",
            options={},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="items", to="shop.color"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="region",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="items", to="shop.region"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="storage",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="items", to="shop.storage"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="discount",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="quantity",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="DeliveryDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="addresses",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="image_payed",
            field=models.FileField(blank=True, null=True, upload_to="pay/image"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_pay",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cart.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="shop.product",
            ),
        ),
    ]
