# Generated by Django 5.1.6 on 2025-04-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_discountcode_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="region",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="storage",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="region",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="storage",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
