# Generated by Django 5.1.6 on 2025-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_orderitem_color_remove_orderitem_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
