# Generated by Django 5.2.3 on 2025-06-26 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_remove_address_intrducer_user_intrducer"),
        ("cart", "0004_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="addresses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="account.address",
            ),
        ),
    ]
